dist: bionic
services: mongodb
before_script:
- cd user
- cp .env.example .env
language: go
go:
- 1.15
script:
- go build
- go test -cover
- go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    rooms:
      - secure: "kMLPrJBkVRnAkkjB4U5tCnwGXdx86sxQp5k2GtrFcNWDEYjbY8oYMfDoTda6lhjymT/zAszAX5UhSRW9wfwnYXgce3Oa6EaQnBhDgvYHVJGZOs0JfMMeSrlVhzKpaYyruI/uFEBVxCpcTPyBKcO2+AmHkpG5htU18pFMZAb6TjwLKbIe+dsvcxR+WSx7h6xSdkKZX+UPaCHxmnM683mPKZJBsj4D3lJxZu2jUGIJ80EQszxK+NzhiOChhh3FNzt9A7UeBXKa2D5xFhcUw+m6b3iJY14GszI+sQ0D6m3yb+sJyBXUlNTg8GroIN5deLvjEkoMf1Nawc44lpOH1VxZCjeW8S2ACOQQckjEGnKCuDZRmcjS7R/SgyiWTNznr9LLf6OXaaNZN24H1Od9Hhch3/c9U3VmRJB/FOeRicJqSdi5ORMGSP55EIS9tfsm5+Y4Pe+B0fxlsb7uOknaqSm63u7t0vRz3Uo1RRJFPUpUWDWbdu05LVFZTvm9k6ZBQRKBTgpuZHoph90uX6fQoI0LatK4Dn+9QfnGlLsHf6pPqY/kDthUGDnTYFutNZLjoHJwKTwCiRr4hRpPuN/9o5wu1V61N0cSkQSEbtWb+NEQIQnTBHoDbptuC5732KDsvxhNdIF98rALe6rcgHubQ/ixX4msnKKk5y8zQkEaS4PoJZo="
      - secure: "OC2tIAisvQ0n+I6X2CDYua4VB8Zby2hrRblzylC03HvOLg+7zuIanmeN6q/SRGIHesZARLStpghK2sknp8bZ9FyGpU6sBLbAQ0bV6pgqaxqnFvbamytmNYRfNkso83cKOse1dYmlQrbum/QuFO1DNO1BMixK9EL5gMdpg8wERUa7vXwBqlrlXYtzNBZ2sKCmT8GBs16t/iZYprYwZXSQq5kXYkT3Xu/WHX6D9c7kFQkRZJAuCOrNSOtXIPye9Y8UkkV7WXX44ToUV7o6+fpbmi2vapz4YGncHgwfcW3vj9nXrRBycbaUxDT4t4XJ8yaUUmwwQjeVJrA0LU8ZQP+Une14RpyGOd8YgajOZLO2o3g0aPlU2adbYJsXvoM4sZtYoWgZ92VtFvN3xPu7KreobdO2C00xC8iJa+HwppjhyqAQEArnX6vX0vJ3EMmk6Y78MSvfBgilRBiXaeyPKVwYQkTKYk879KHD3niylunAUC67NvjgwrBsB8sEl/VwSvLlmPuHmDBeDRePJ3XOeCPo8V+lBvOJSObDNEipVPkZUm1XkJZVJhg5No9YUvUee//71ni1y5MK4T9AZlqAWfr6Jr+ZJFoJ8nid9CY+EIXj4ZDfHWfFPSEOEyI4R7Taq5B9+hMINS4QICFXG4h5LqJksLh0eTQ9DC/lNNsmLg6WVoY="