dist: bionic
language: go
go:
- "1.15"
script:
- go build ./..
- go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    rooms:
      - secure: "nTX2sgUf81O7Ggun+jlBptdJq8sefbb9O30lzGdu6cWihSNpcAcZ6zL5GyXQkBbJP1g6IzfP3Et/rH/aVNOrZPEDN8kUNgcRQQXXAd2Do8IJZBbj3mdKDqlnx62D1lcf7woj9/wU+xymvyl18Q9yUfqTFHIKs5O4uvnIQfiQfBRZp7CIii7oVFPWuOgNHtXytk1Q+5RQg3/7FdMJm3oynZD5DK7RsrsyhHs9+9IWTLbrcvEZuV0jz6xOGP9EW1qomNctJzQHLWHI1gLSSxy6HGUaNTpvyuTbn8EotCBT9t3gBq6CkSmeVKG+u6dV6N4jK3U0Fzdv1kD4Z6PIY/zVUEQXhj6NNLVULRKIvWwvbvEBCDtRmgbFA3dELNjEci0EszrEzvqZq+AztM8bzWYHEpWX3uG8wDKpwjZeQ/DpOTM9qTCtMqQdjWwIldm5Iwuknopwr08q7s9KFJxf5vpj7PPeZNbI/96SgiuQWNRkEVd+tYcAI8/pDu71mylPIj50P6B2gLxt9ADiXAjsmLiQqjb7aXIrst1TmpmBTV1NRyqwYiD/YvzVw6FARJ0NkRs2BNV52GuqeotV5/jbl44Jv7aNdCvLZRdT23yvId6tqrwv5r4ODJqAezxOWtsyW4DN5gZeQkIUJYII+ie+8slXZw5v0/pU8ytehB0WZZFLnbI="
      - secure: "OC2tIAisvQ0n+I6X2CDYua4VB8Zby2hrRblzylC03HvOLg+7zuIanmeN6q/SRGIHesZARLStpghK2sknp8bZ9FyGpU6sBLbAQ0bV6pgqaxqnFvbamytmNYRfNkso83cKOse1dYmlQrbum/QuFO1DNO1BMixK9EL5gMdpg8wERUa7vXwBqlrlXYtzNBZ2sKCmT8GBs16t/iZYprYwZXSQq5kXYkT3Xu/WHX6D9c7kFQkRZJAuCOrNSOtXIPye9Y8UkkV7WXX44ToUV7o6+fpbmi2vapz4YGncHgwfcW3vj9nXrRBycbaUxDT4t4XJ8yaUUmwwQjeVJrA0LU8ZQP+Une14RpyGOd8YgajOZLO2o3g0aPlU2adbYJsXvoM4sZtYoWgZ92VtFvN3xPu7KreobdO2C00xC8iJa+HwppjhyqAQEArnX6vX0vJ3EMmk6Y78MSvfBgilRBiXaeyPKVwYQkTKYk879KHD3niylunAUC67NvjgwrBsB8sEl/VwSvLlmPuHmDBeDRePJ3XOeCPo8V+lBvOJSObDNEipVPkZUm1XkJZVJhg5No9YUvUee//71ni1y5MK4T9AZlqAWfr6Jr+ZJFoJ8nid9CY+EIXj4ZDfHWfFPSEOEyI4R7Taq5B9+hMINS4QICFXG4h5LqJksLh0eTQ9DC/lNNsmLg6WVoY="