dist: bionic
services: mongodb
before_script:
- cd user
- cp .env.example .env
language: go
go:
- 1.15
script:
- go build
- go test -cover
- go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: nGBVGJ8PziHzdTof7d+ezdkGoRzMztF6aHR9YFQYA1CkE4At1HShtyGsiZH3CUj0iRgf8/9S/YE+aFoieZSGUlfYgq3j5VXnvzmXM0ddwkmafWZyO5ths0qT084DgONttLVxj5imH6ZT4cOPI0mV8fHUN/6JnomUsbgfw+AuUiA6wpgfGSePj22BAE6hdxL9iveI1V4L0aSoi+/uT1Z/TKxksFIcBpsPqmZrhABfm8PwDRE5+Hy2gJEa3veyds2+TF6yViUHHPpNKOS1lMkZUJP67DuFw4iJ+6IB1eM2a+HBoycF6nY2OjA5eIzoRCRR/44NV+E+F/g2kI/dF3XToJ5MQB+AUAFKNjJooCLopDhuSX9AuWtQTcaXTJaoK8/N51sy2JYQjKYPCtMmJpr3RbuO3GpqvdLE5qPhZPr6e7J1kO/XZ6jP1+d8lg/l3BOJhJ0BNO7cPLDwyR+BJ2acACbitFpHjC3Gbjc0gqpfpK3JoF0CNXM5YSGm9vBnTtBeBB6aMq4vz2A+YnsUHx+xP2C/xDHDCvnEyy2NtTC5h5rNbi5g7QG+YaYFXLJnJBXaHeU2QzLB0ZucPJHUsN33tOdAhqmO8bcxCQcY+Agzt8MLNBoYRrfh+HNtzn/f5c9hhXTVFCzoCuIFwnthEzJ3RKj0uHbYaBEIL91uVQ0bfXA=
root@a8371fb5c852:/NCNUOJBackend#
    rooms:
	    - vincentinttsh:5ZJnFhOXSTTJHFfPzs65uLXW#backend